sudo: required

services:
  - docker

before_install:
  - docker build -t gloria101987/app -f Dockerfile.dev .

script:
  - docker run gloria101987/app npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-app"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-39383838"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY